/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.co.qhodok.nlp.MachinTranslationAPP;

import javax.swing.JFileChooser;

/**
 *
 * @author Andika
 */
public class FormTraining extends javax.swing.JFrame {

    /**
     * Creates new form LATIH
     */
    protected FormTesting formTesting;
    protected JFileChooser fileChooser;
    public FormTraining(FormTesting formTesting) {
        this.formTesting = formTesting;
        this.fileChooser = new JFileChooser();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        englishCorpusTextField = new javax.swing.JTextField();
        indCorpusTextField = new javax.swing.JTextField();
        dictTextField = new javax.swing.JTextField();
        englishCorpusButton = new javax.swing.JButton();
        IndButtonCorpus = new javax.swing.JButton();
        dictButtonCorpus = new javax.swing.JButton();
        trainingButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        testingMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("English Corpus");

        jLabel2.setText("Indonesi Cospus");

        jLabel3.setText("DIctionary");

        englishCorpusTextField.setEditable(false);
        englishCorpusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishCorpusTextFieldActionPerformed(evt);
            }
        });

        indCorpusTextField.setEditable(false);

        dictTextField.setEditable(false);

        englishCorpusButton.setText("search");
        englishCorpusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishCorpusButtonActionPerformed(evt);
            }
        });

        IndButtonCorpus.setText("search");

        dictButtonCorpus.setText("search");

        trainingButton.setText("training");

        jMenu1.setText("File");

        testingMenu.setText("Buka Halaman Testing ");
        testingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testingMenuActionPerformed(evt);
            }
        });
        jMenu1.add(testingMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(indCorpusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IndButtonCorpus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dictTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dictButtonCorpus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(englishCorpusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(englishCorpusButton))))
                    .addComponent(trainingButton))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(englishCorpusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(englishCorpusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(indCorpusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IndButtonCorpus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dictTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dictButtonCorpus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trainingButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testingMenuActionPerformed
        this.formTesting.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testingMenuActionPerformed

    private void englishCorpusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishCorpusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishCorpusTextFieldActionPerformed

    private void englishCorpusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishCorpusButtonActionPerformed
       
    }//GEN-LAST:event_englishCorpusButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IndButtonCorpus;
    private javax.swing.JButton dictButtonCorpus;
    private javax.swing.JTextField dictTextField;
    private javax.swing.JButton englishCorpusButton;
    private javax.swing.JTextField englishCorpusTextField;
    private javax.swing.JTextField indCorpusTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem testingMenu;
    private javax.swing.JButton trainingButton;
    // End of variables declaration//GEN-END:variables
}
